name: Branch Deleted

on:
  delete:
    branches:
      - 'feature/**'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: mathiasgheno/s3-on-demand-action@main
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'www'
          ACTION: 'delete'
